SELECT TO_CHAR(CURRENT TIMESTAMP, 'hhmiss')
FROM SYSIBM.SYSDUMMY1
;
SELECT TO_CHAR(CURRENT TIMESTAMP, 'yyyyMMdd'), TO_CHAR(CURRENT DATE, 'yyyyMMdd')
FROM SYSIBM.SYSDUMMY1
;
SELECT SUBSTRING(CHAR(CURRENT DATE, ISO), 1, 4) || SUBSTRING(CHAR(CURRENT DATE, ISO), 6, 2) || SUBSTRING(CHAR(CURRENT DATE, ISO), 9, 2)
FROM SYSIBM.SYSDUMMY1
;
